import { StyleSheet } from 'react-native';
import { COLORS, DIMENSIONS, FONT, SIZES } from '../../constants/constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF5F3',
  },
  text: {
    fontSize: 24,
    fontFamily: FONT.GE_SS_Bold,
    color: COLORS.DarkTextColor,
    marginBottom: 10,
  },
  subtext: {
    fontSize: 16,
    fontFamily: FONT.GE_SS_Medium,
    color: COLORS.LightTextColor,
  },

  sheet: {
    flex: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 10,
    overflow: 'hidden',
  },
  sheetHandleContainer: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: 10,
  },
  sheetHandle: {
    width: 48,
    height: 6,
    borderRadius: 4,
    backgroundColor: '#e0e0e0',
  },
  sheetContent: {
    padding: 16,
    flex: 1,
  },
  sheetInnerContent: {
    flex: 1,
    paddingBottom: 32,
    alignItems: 'flex-end',
  },

  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },

  // request type
  requestTypeContainer: {
    position: 'relative',
    width: 290,
    height: 35,
    backgroundColor: COLORS.borderColor,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    padding: 4,
    overflow: 'hidden',
  },
  optionTouchable: {
    flex: 1,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    zIndex: 2,
  },
  activeOption: {
    flex: 1,
    height: '100%',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  inactiveOption: {
    flex: 1,
    height: '100%',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  optionTextActive: {
    fontSize: SIZES.small,
    fontFamily: FONT.GE_SS_Medium,
    color: COLORS.whiteTextColor,
    width: 80,
    textAlign: 'right',
    paddingRight: 12,
  },
  optionTextInactive: {
    fontSize: SIZES.small,
    fontFamily: FONT.GE_SS_Medium,
    color: COLORS.ExtraLightTextColor,
    width: 80,
    textAlign: 'right',
    paddingRight: 12,
  },
  requestTypeSlider: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '50%',
    height: 35,
    borderRadius: 20,
    zIndex: 0,
  },
  selfOrderContainer: {
    alignItems: 'flex-end',
  },

  inputTitleStyles: {
    marginTop: 24,
    color: COLORS.DarkTextColor,
    fontSize: SIZES.large,
    fontFamily: FONT.GE_SS_Light,
  },
  problemTypesContainer: {
    height: 150,
  },
  problemTypeCard: {
    backgroundColor: COLORS.borderColor,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    height: 120,
    width: 160,
  },
  activeProblemTypeCard: {
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    height: 120,
    width: 160,
    overflow: 'hidden',
  },
  problemTypeIconPlaceholder: {
    backgroundColor: COLORS.bgColor,
    borderRadius: 8,
    padding: 8,
  },
  activeProblemTypeIconPlaceholder: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  activeIconGlow: {
    position: 'absolute',
    left: -10,
    right: -10,
    top: -10,
    elevation: 22,
    zIndex: 150,
    borderRadius: 16,
    opacity: 0.9,
  },
  activeIconInnerShadow: {
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.6,
    shadowRadius: 18,
    elevation: 18,
  },
  problemTypeIcon: {
    width: 60,
    height: 60,
    resizeMode: 'contain',
    borderRadius: 8,
  },
  problemTypeLabel: {
    color: COLORS.DarkTextColor,
    fontSize: SIZES.small,
    fontFamily: FONT.GE_SS_Light,
    marginTop: 8,
  },
  activeProblemTypeLabel: {
    color: COLORS.whiteTextColor,
    fontSize: SIZES.small,
    fontFamily: FONT.GE_SS_Light,
    marginTop: 8,
  },
  activeProblemGlow: {
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.45,
    shadowRadius: 22,
    elevation: 20,
  },
  activeGlowLayer: {
    position: 'absolute',
    left: -12,
    right: -12,
    top: -12,
    bottom: -12,
    borderRadius: 20,
    zIndex: 0,
    opacity: 0.35,
  },

  carTypeInput: {
    marginTop: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 2,
    borderColor: COLORS.borderColor,
    borderRadius: 8,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
    fontFamily: FONT.Montserrat_Regular,
    textAlign: 'right',
  },

  journeyContainer: {
    marginTop: 8,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
  },
  rightBarHolder: {
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  activeLocationCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
  },
  inactiveLocationCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.ExtraLightTextColor,
  },
  dotsIcon: {
    marginVertical: 4,
    width: 4,
  },
  locationTextsHolder: {
    alignItems: 'flex-end',
  },
  locationDesc: {
    fontSize: SIZES.small,
    fontFamily: FONT.GE_SS_Light,
    color: COLORS.ExtraLightTextColor,
  },
  locationAddress: {
    fontSize: SIZES.medium,
    fontFamily: FONT.GE_SS_Light,
    color: COLORS.DarkTextColor,
  },
  selectedDestinationRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
    width: DIMENSIONS().screenWidth - 60,
  },
  selectedDestinationText: {
    flex: 1,
    textAlign: 'right',
    fontSize: SIZES.medium,
    fontFamily: FONT.Montserrat_Light,
    color: COLORS.DarkTextColor,
  },
  selectedDestinationClear: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  selectedDestinationClearText: {
    fontSize: SIZES.xsmall,
    fontFamily: FONT.GE_SS_Medium,
    color: COLORS.LightTextColor,
  },
  secondLocationDesc: {
    fontSize: SIZES.small,
    fontFamily: FONT.GE_SS_Light,
    color: COLORS.ExtraLightTextColor,
    paddingTop: 44,
  },
  addDestinationButton: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.borderColor,
    height: 35,
    paddingHorizontal: 12,
    borderRadius: 10,
    width: DIMENSIONS().screenWidth - 60,
    justifyContent: 'flex-start',
    alignSelf: 'stretch',
  },
  addDestinationButtonText: {
    fontSize: SIZES.small,
    fontFamily: FONT.GE_SS_Light,
    color: COLORS.LightTextColor,
  },

  destSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    overflow: 'hidden',
  },
  destHandleContainer: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: 10,
  },
  destHandle: {
    width: 48,
    height: 6,
    borderRadius: 4,
    backgroundColor: '#e0e0e0',
  },
  destHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  destTitle: {
    fontSize: SIZES.large,
    fontFamily: FONT.GE_SS_Light,
    color: COLORS.DarkTextColor,
  },
  destClose: {
    fontSize: SIZES.small,
    fontFamily: FONT.GE_SS_Medium,
    color: COLORS.primary,
  },
  destSearchRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
    backgroundColor: COLORS.borderColor,
    marginHorizontal: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
  },
  destSearchInputWrap: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  destSearchInput: {
    flex: 1,
    textAlign: 'right',
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
  },
  destSuggestions: {
    marginHorizontal: 16,
    marginTop: 6,
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: COLORS.borderColor,
    overflow: 'hidden',
    maxHeight: 220,
  },
  destSuggestionRow: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderColor,
  },
  destSuggestionMain: {
    fontSize: SIZES.medium,
    fontFamily: FONT.GE_SS_Medium,
    color: COLORS.DarkTextColor,
    textAlign: 'right',
  },
  destSuggestionSecondary: {
    fontSize: SIZES.small,
    fontFamily: FONT.GE_SS_Light,
    color: COLORS.LightTextColor,
    textAlign: 'right',
    marginTop: 2,
  },
  destMapHolder: {
    flex: 1,
    marginTop: 12,
    marginHorizontal: 16,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.borderColor,
    position: 'relative',
  },
  destPinOverlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -12,
    marginTop: -24,
    zIndex: 5,
    alignItems: 'center',
  },
  destPinShadow: {
    width: 16,
    height: 4,
    borderRadius: 4,
    backgroundColor: 'rgba(0,0,0,0.25)',
    transform: [{ scaleX: 1.2 }],
    marginTop: 4,
  },
  destConfirmButton: {
    marginHorizontal: 16,
    marginVertical: 16,
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 12,
  },
  destConfirmText: {
    color: COLORS.whiteTextColor,
    fontSize: SIZES.medium,
    fontFamily: FONT.GE_SS_Medium,
  },

  priceContainer: {
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: COLORS.borderColor,
    flexDirection: 'column',
    gap: 16,
    width: DIMENSIONS().screenWidth - 30,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
  },
  priceAdjustBtn: {
    width: 54,
    height: 54,
    borderRadius: 10,
    backgroundColor: '#f55a2c',
    alignItems: 'center',
    justifyContent: 'center',
  },
  priceAdjustBtnDisabled: {
    backgroundColor: '#d9d9d9',
  },
  priceAdjustText: {
    color: '#fff',
    fontSize: 28,
    lineHeight: 32,
  },
  priceAdjustTextDisabled: {
    color: '#888',
  },
  priceAmountWrap: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
  },
  priceAmountText: {
    fontSize: 36,
    fontWeight: '800',
    color: '#0a0a0a',
  },
  priceCurrencyText: {
    fontSize: 18,
    color: '#111',
  },
  submitBtnWrapper: {
    marginTop: 16,
    width: DIMENSIONS().screenWidth - 30,
  },
  submitGradient: {
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  submitText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '700',
  },
  submitTextDisabled: {
    color: '#777',
  },

  // Ride progress
  rideProgressBar: {
    position: 'absolute',
    top: 32,
    left: 16,
    right: 16,
    zIndex: 200,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#ff6b36',
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 12,
  },
  rideProgressStep: {
    minWidth: 90,
    paddingHorizontal: 12,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    borderRadius: 28,
    flexDirection: 'row',
  },
  rideProgressStepActive: {
    backgroundColor: '#ff6b36',
  },
  rideProgressLabel: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
  },
  rideProgressLabelActive: {
    color: '#fff',
    fontFamily: FONT.GE_SS_Medium,
  },
  rideProgressArrow: {
    marginHorizontal: 6,
  },

  // Offers overlay
  offersOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 28,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(0,0,0,0.16)',
    pointerEvents: 'box-none',
  },
  offersHeader: {
    alignItems: 'center',
    marginBottom: 12,
  },
  cancelTripButton: {
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 14,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  cancelTripText: {
    color: '#d32f2f',
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.medium,
  },
  offersList: {
    backgroundColor: 'transparent',
  },
  offersTitle: {
    textAlign: 'center',
    color: COLORS.DarkTextColor,
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.large,
    marginBottom: 10,
  },
  offersScroll: {
    paddingBottom: 110,
    paddingHorizontal: 6,
  },
  offerCard: {
    borderRadius: 18,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 6,
    marginBottom: 22,
    width: DIMENSIONS().screenWidth - 24,
  },
  offerHeaderRow: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 65,
    borderRadius: 45,
    width: DIMENSIONS().screenWidth - 24,
  },
  offerTimerBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    paddingLeft: 4,
  },
  offerTimerRingOuter: {
    width: 52,
    height: 52,
    marginLeft: 4,
    borderRadius: 31,
    borderWidth: 5,
    borderColor: '#f16c5b',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fdecea',
  },
  offerTimerRingInner: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerTimerText: {
    fontFamily: FONT.Montserrat_Semi_Bold,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
  },
  offerMeta: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 2,
  },
  offerMetaText: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
    textAlign: 'left',
    lineHeight: 16,
    direction: 'rtl',
  },
  offerMetaTextNumber: {
    fontFamily: FONT.Montserrat_Regular,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
  },
  offerPriceBlock: {
    flex: 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  offerPriceBlockInner: {
    alignItems: 'flex-end',
  },
  offerPriceValue: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.medium,
    color: '#e65100',
  },
  offerPriceValueNumber: {
    fontFamily: FONT.Montserrat_Semi_Bold,
    fontSize: SIZES.large,
    color: '#e65100',
  },
  offerPriceLabel: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
    marginTop: 2,
  },
  offerDriverBlock: {
    alignItems: 'flex-end',
    gap: 2,
  },
  offerDriverId: {
    fontFamily: FONT.Montserrat_Regular,
    fontSize: SIZES.xsmall,
    color: COLORS.LightTextColor,
  },
  offerDriverName: {
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
    maxWidth: 75,
    textAlign: 'right',
  },
  offerRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
  },
  offerAvatar: {
    width: 52,
    height: 52,
    borderRadius: 32,
    marginRight: 4,
    marginLeft: 4,
  },
  offerActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    gap: 10,
  },
  offerRejectBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#e53935',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerRejectText: {
    color: '#fff',
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.medium - 1,
  },
  offerAcceptBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#15b565',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerAcceptBtnActive: {
    backgroundColor: '#0d8f4f',
  },
  offerAcceptText: {
    color: '#fff',
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.medium - 1,
  },

  // Active trip card
  activeTripCard: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 150,
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 22,
    borderWidth: 1,
    borderColor: COLORS.borderColor,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: -2 },
    elevation: 22,
  },
  activeTripHandle: {
    width: 50,
    height: 6,
    borderRadius: 4,
    backgroundColor: '#e0e0e0',
    alignSelf: 'center',
    marginBottom: 12,
  },
  activeTripHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  activeTripInfo: {
    alignItems: 'flex-end',
    gap: 4,
    flex: 1,
    paddingRight: 10,
  },
  activeTripName: {
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.large,
    color: COLORS.DarkTextColor,
    textAlign: 'right',
  },
  activeTripPhone: {
    fontFamily: FONT.Montserrat_Regular,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
    textAlign: 'right',
  },
  activeTripPlate: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
    textAlign: 'right',
  },
  activeTripPlateNumber: {
    fontFamily: FONT.Montserrat_Regular,
  },
  activeTripAvatar: {
    width: 64,
    height: 64,
    borderRadius: 36,
    backgroundColor: COLORS.borderColor,
  },
  activeTripMetaRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    gap: 10,
  },
  activeTripMetaBlock: {
    flex: 1,
    alignItems: 'flex-end',
    gap: 4,
  },
  activeTripMetaLabel: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
  },
  activeTripMetaValue: {
    fontFamily: FONT.Montserrat_Regular,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
  },
  activeTripStatusPill: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: '#ffe3d7',
  },
  activeTripStatusText: {
    color: '#e65100',
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.small,
  },
  activeTripActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 6,
    marginBottom: 10,
  },
  activeTripCallBtn: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#2a87d3',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  activeTripWhatsBtn: {
    backgroundColor: '#25D366',
  },
  activeTripNote: {
    textAlign: 'center',
    color: COLORS.LightTextColor,
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    marginTop: 4,
  },
});

export default styles;