import { StyleSheet } from 'react-native';
import { COLORS, FONT, SIZES } from '../../constants/constants';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f7fa',
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
  },
  headerTitle: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: 16,
    color: COLORS.DarkTextColor,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  mapContainer: {
    height: 240,
    backgroundColor: '#e9edf3',
  },
  map: {
    flex: 1,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    overflow: 'hidden',
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    zIndex: 1,
  },
  requestsSlider: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#f5f6f8',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 0,
    paddingBottom: 8,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -2 },
    elevation: 6,
    zIndex: 2,
  },
  sheetHandleContainer: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetHandle: {
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#d1d5db',
  },
  filtersRow: {
    paddingHorizontal: 14,
    maxHeight: 60,
  },
  filtersContent: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
    paddingRight: 6,
    paddingVertical: 14,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#e8e9ec',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterChipActive: {
    backgroundColor: '#d9dbdf',
  },
  filterChipText: {
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
  },
  listContainer: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 6,
    paddingBottom: 40,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  cardRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  riderInfo: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  riderInfoText: {
    justifyContent: 'center',
    alignItems: 'flex-end',
    gap: 2,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#ffe4d4',
  },
  name: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  metaText: {
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
  },
  metaTextData: {
    fontFamily: FONT.Montserrat_Bold,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
  },
  price: {
    fontFamily: FONT.Montserrat_Bold,
    fontSize: 22,
    color: COLORS.DarkTextColor,
  },
  currency: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: 14,
    color: COLORS.LightTextColor,
  },
  detailsButton: {
    marginTop: 12,
    alignSelf: 'flex-end',
    backgroundColor: '#f24c2d',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  detailsButtonText: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.small,
    color: '#fff',
  },
  tripDetailsSlider: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#f5f6f8',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -2 },
    elevation: 6,
    zIndex: 2,
  },
  tripDetailsHandleContainer: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tripDetailsHandle: {
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#d1d5db',
  },
  tripDetailsContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 0,
  },
  tripDetailsHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    marginBottom: 20,
  },
  tripDetailsHeaderDots: {
    alignItems: 'center',
    marginLeft: 12,
  },
  tripDetailsDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#d1d5db',
  },
  tripDetailsDotRed: {
    backgroundColor: COLORS.primary,
  },
  tripDetailsLine: {
    width: 2,
    height: 40,
    backgroundColor: '#d1d5db',
    marginVertical: 4,
  },
  tripDetailsAddresses: {
    flex: 1,
    justifyContent: 'space-between',
    height: 64,
  },
  tripDetailsAddress: {
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
    textAlign: 'right',
  },
  tripDetailsAddressNumber: {
    fontFamily: FONT.Montserrat_Bold,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
  },
  tripDetailsAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#ffe4d4',
  },
  tripDetailsInfo: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  tripDetailsInfoRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  tripDetailsLabel: {
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
  },
  tripDetailsValue: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
  },
  tripDetailsValueNumber: {
    fontFamily: FONT.Montserrat_Bold,
  },
  bidSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  bidLabel: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.large,
    color: COLORS.primary,
    marginBottom: 16,
  },
  bidControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  bidButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#e8e9ec',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bidButtonText: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: 24,
    color: COLORS.DarkTextColor,
  },
  bidPrice: {
    fontFamily: FONT.Montserrat_Bold,
    fontSize: 32,
    color: COLORS.DarkTextColor,
    minWidth: 80,
    textAlign: 'center',
  },
  tripDetailsActions: {
    flexDirection: 'row',
    gap: 12,
  },
  submitBidButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitBidButtonText: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
    color: '#fff',
  },
  backButton: {
    backgroundColor: '#e8e9ec',
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
  },
});
