import { StyleSheet } from 'react-native';
import { COLORS, FONT, SIZES } from '../../constants/constants';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgColor,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  heroCard: {
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 24,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    gap: 20,
  },
  heroCircles: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  circle: {
    flex: 1,
    maxWidth: 200,
    aspectRatio: 1,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    overflow: 'hidden',
  },
  progressWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleInner: {
    width: '78%',
    height: '78%',
    borderRadius: 120,
    backgroundColor: COLORS.bgColor,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 8,
  },
  circleLabelBalance: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
    textAlign: 'center',
  },
  circleValueBalance: {
    fontFamily: FONT.Montserrat_Semi_Bold,
    fontSize: SIZES.medium,
    color: COLORS.primary,
    textAlign: 'center',
  },
  circleLabelSub: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
    textAlign: 'center',
  },
  circleValueSub: {
    fontFamily: FONT.Montserrat_Semi_Bold,
    fontSize: SIZES.medium,
    color: COLORS.primary,
    textAlign: 'center',
  },
  circleSub: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.large,
    color: COLORS.DarkTextColor,
    textAlign: 'center',
  },
  tabsRow: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
  },
  singleTab: {
    flex: 1,
  },
  tabButtonActive: {
    backgroundColor: '#f5f5f5',
  },
  tabButtonInactive: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.6)',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  tabText: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.small,
  },
  tabTextActive: {
    color: COLORS.DarkTextColor,
  },
  tabTextInactive: {
    color: COLORS.whiteTextColor,
  },
  sectionTitle: {
    marginTop: 18,
    marginBottom: 10,
    paddingHorizontal: 18,
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
    textAlign: 'right',
  },
  cardsArea: {
    gap: 14,
    paddingHorizontal: 12,
  },
  planCard: {
    backgroundColor: '#f1f1f3',
    borderRadius: 14,
    overflow: 'hidden',
  },
  planGradient: {
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  planContent: {
    // flexDirection: 'row-reverse',
    gap: 12,
    alignItems: 'center',
  },
  topCard: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    width: '100%',
  },
  cardContentHolder:{
    flexDirection: 'row-reverse',
    gap: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  planRight: {
    flex: 1,
    gap: 6,
    alignItems: 'flex-end',
  },
  planHeaderRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  planTitle: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
    color: COLORS.whiteTextColor,
  },
  statusPill: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 10,
  },
  planLeft: {
    // width: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planIconWrap: {
    width: 110,
    height: 110,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  planIconImage: {
    width: 110,
    height: undefined,
    borderRadius: 18,
    backgroundColor: 'transparent',
    aspectRatio: 1,
  },
  planIconText: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.xLarge,
    color: COLORS.whiteTextColor,
  },
  planPrice: {
    fontFamily: FONT.Montserrat_Semi_Bold,
    fontSize: SIZES.small,
    color: COLORS.whiteTextColor,
  },
  planPriceRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  planPriceOriginal: {
    fontFamily: FONT.Montserrat_Regular,
    fontSize: SIZES.xsmall,
    color: 'rgba(255,255,255,0.8)',
    textDecorationLine: 'line-through',
  },
  planDesc: {
    textAlign: 'right',
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.xsmall,
    color: COLORS.whiteTextColor,
    lineHeight: 18,
    flex: 1,
  },
  planDescRow: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: 6,
  },
  planDescBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginTop: 6,
    backgroundColor: COLORS.whiteTextColor,
  },
  ctaButton: {
    marginTop: 6,
    // alignSelf: 'flex-start',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bgColor,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  ctaText: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.small,
    color: COLORS.primary,
  },
  statusSuccess: {
    backgroundColor: '#19c37d',
  },
  statusWarning: {
    backgroundColor: '#e74c3c',
  },
  statusText: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.xsmall,
  },
  statusTextSuccess: {
    color: COLORS.whiteTextColor,
  },
  statusTextWarning: {
    color: COLORS.whiteTextColor,
  },
  footerNote: {
    marginTop: 16,
    textAlign: 'center',
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
    paddingHorizontal: 18,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  modalCard: {
    width: '100%',
    height: 370,
    backgroundColor: COLORS.bgColor,
    borderRadius: 14,
    padding: 18,
    gap: 14,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  modalTitle: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
    textAlign: 'center',
  },
  modalDescription: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
    textAlign: 'center',
    lineHeight: 20,
  },
  modalDescriptionNumber: {
    fontFamily: FONT.Montserrat_Regular,
    fontSize: SIZES.small,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: COLORS.borderColor,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontFamily: FONT.Montserrat_Regular,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
    backgroundColor: '#fff',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    height:40
  },
  modalButtonSecondary: {
    borderWidth: 1,
    borderColor: COLORS.borderColor,
    backgroundColor: '#fff',
    height:40
  },
  modalButtonPrimary: {
    backgroundColor: COLORS.primary,
    height:40
  },
  modalButtonSecondaryText: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
    height:40
  },
  modalButtonPrimaryText: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.small,
    color: COLORS.whiteTextColor,
  },
});
