import { StyleSheet } from 'react-native';
import { COLORS, FONT, SIZES } from '../../constants/constants';

export default StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: COLORS.bgColor,
  },
  scroll: {
    flex: 1,
    backgroundColor: COLORS.bgColor,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: COLORS.bgColor,
  },
  contentSpacer: {
    paddingBottom: 80,
  },
  backBtn: {
    marginBottom: 14,
    marginTop: 32,
    zIndex: 10,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  backText: {
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.medium,
    color: COLORS.primary,
  },
  statusBar: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff7f3',
    borderWidth: 1,
    borderColor: '#ffd8cc',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 18,
  },
  statusTitle: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
  },
  statusValue: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
    color: COLORS.primary,
  },
  infoBanner: {
    backgroundColor: '#fff7f3',
    borderWidth: 1,
    borderColor: '#ffd8cc',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 16,
  },
  infoTitle: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
    color: COLORS.primary,
    textAlign: 'right',
    marginBottom: 4,
  },
  infoBody: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.DarkTextColor,
    textAlign: 'right',
    lineHeight: 20,
  },
  uploadCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderColor,
    backgroundColor: '#fff',
    padding: 16,
    marginBottom: 16,
  },
  uploadHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  uploadLabel: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
    textAlign: 'right',
  },
  reuploadHint: {
    fontFamily: FONT.GE_SS_Medium,
    fontSize: SIZES.xsmall,
    color: COLORS.primary,
  },
  uploadButton: {
    alignSelf: 'stretch',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  uploadButtonText: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.small,
    color: COLORS.primary,
  },
  helperText: {
    marginTop: 10,
    textAlign: 'right',
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.xsmall,
    color: COLORS.LightTextColor,
  },
  previewImage: {
    width: '100%',
    height: 180,
    borderRadius: 12,
    marginTop: 12,
  },
  inputBlock: {
    marginBottom: 16,
  },
  inputLabel: {
    fontFamily: FONT.GE_SS_Light,
    fontSize: SIZES.small,
    color: COLORS.LightTextColor,
    textAlign: 'right',
    marginBottom: 6,
  },
  textInput: {
    fontFamily: FONT.Montserrat_Semi_Bold,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
    textAlign: 'right',
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.borderColor,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  vehicleOptionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  vehicleCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: '#f5f6fb',
    borderWidth: 1,
    borderColor: '#e6e8f0',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  vehicleCardActive: {
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  vehicleCardInner: {
    flex: 1,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  vehicleCardInnerActive: {
    borderRadius: 18,
  },
  vehicleIcon: {
    width: 90,
    height: 70,
  },
  vehicleLabel: {
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
    color: COLORS.DarkTextColor,
  },
  vehicleLabelActive: {
    color: COLORS.whiteTextColor,
  },
  submitButton: {
    width: '100%',
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 24,
  },
  submitButtonDisabled: {
    opacity: 0.8,
  },
  submitText: {
    color: COLORS.whiteTextColor,
    fontFamily: FONT.GE_SS_Bold,
    fontSize: SIZES.medium,
  },
});
